
development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  adapter: redis
  url: redis://redistogo:1b45d2c9d0f111c93147affd3d2730e5@dory.redistogo.com:10575/
