
development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://redistogo:69e60df416417ca19905a2505081d5b5@dory.redistogo.com:10370/
  :host: dory.redistogo.com
  :port: 10370
  :password: 349f93483fv9erfv849dfv4892kascnj
  :inline: true
  :timeout: 1
